### ISSUE TITLE
experiments: add GHA workflow with CML and Studio Live metrics

### ISSUE THREAD

**Issue by alex000kim** [iterative/example-repos-dev#168]
`run-studio-experiments.yaml`:

```yaml
name: CML
on: 
  push:
    paths:
      - ".github/workflows/run-experiment.yaml"
      - "data/**"
      - "src/**"
      - "params.yaml"
      - "dvc.*"
jobs:
  deploy-runner:
    if: github.actor == 'iterative-studio[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Create Runner
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          cml runner launch --single \
            --labels=cml \
            --cloud=aws \
            --cloud-region=us-east \
            --cloud-hdd-size=40 \
            --cloud-type=g5.2xlarge
  runner-job:
    needs: deploy-runner
    runs-on: [ self-hosted, cml ]
    container:
      image: iterativeai/cml:0-dvc2-base1-gpu
      options: --gpus all --ipc host
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: training
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          STUDIO_TOKEN: ${{ secrets.STUDIO_TOKEN }}
          DVCLIVE_LOGLEVEL: DEBUG
        run: |
          pip install -r requirements.txt
          dvc pull
          cml comment create --publish --watch results/train/report.md & dvc repro
          dvc push
          cml pr --squash --skip-ci .
          cml comment create --pr --publish results/evaluate/report.md

```
